name: 'Auto utpdate flake lock file'

on:
  workflow_call: ~
  workflow_dispatch:

jobs:
  auto-upgrade-flake-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Update flake.lock
        run: |
          git config --global user.name 'loophp[bot]'
          git config --global user.email 'd.paolino+bot@users.noreply.github.com'
          nix flake update --commit-lock-file --commit-lockfile-summary "$COMMIT_MSG"

      - name: Push changes
        run: |
          git config --global user.name 'loophp[bot]'
          git config --global user.email 'd.paolino+bot@users.noreply.github.com'
          git push
