name: 'Auto utpdate flake lock file'

on:
  workflow_call: ~
  workflow_dispatch:

jobs:
  auto-upgrade-flake-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
          echo "trusted-users = root worker" | sudo tee -a /etc/nix/nix.conf
          echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
          sudo systemctl restart nix-daemon

      - name: Update flake.lock
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          nix flake update --commit-lock-file --commit-lockfile-summary "$COMMIT_MSG"

      - name: Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git push
