name: "Test flake lock file update workflow"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Everyday Monday at midnight, see https://crontab.guru/ for more examples

jobs:
  createPullRequest:
    uses: loophp/flake-lock-update-workflow/.github/workflows/upgrade-flakes.yaml@main
