name: "Test flake lock file update workflow"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Everyday at 6am, see https://crontab.guru/ for more examples

jobs:
  createPullRequest:
    uses: loophp/flake-lock-update-workflow/.github/workflows/upgrade-flakes.yaml@main
