name: 'Update flake lock file'

on:
  workflow_call: ~
  workflow_dispatch:

jobs:
  updateFlakeLock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
