name: 'Update flake lock file'

on:
  workflow_call:
    secrets:
      token:
        description: 'A token passed from the caller workflow to trigger tests on the pull request.'
        required: true
  workflow_dispatch:

jobs:
  updateFlakeLock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.token }}