name: 'Update flake lock file'

on:
  workflow_call: ~
  workflow_dispatch:

jobs:
  updateFlakeLock:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v18
