name: 'Update flake lock file'

on:
  workflow_call:
    secrets:
      token:
        description: 'A token passed from the caller workflow to trigger tests on the pull request.'
        required: true
  workflow_dispatch:

jobs:
  updateFlakeLock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
          echo "trusted-users = root worker" | sudo tee -a /etc/nix/nix.conf
          echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
          sudo systemctl restart nix-daemon

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.token }}
